# Generated by Django 4.2.4 on 2023-08-31 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_film_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.CharField(max_length=500),
        ),
    ]
